# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.50335946 0.33632777 0.95340658]
  [0.97636394 0.4499742  0.72862481]
  [0.82445854 0.51445753 0.9635533 ]]

 [[0.36181392 0.27209729 0.92400059]
  [0.51979632 0.54332201 0.73276163]
  [0.85891967 0.82115938 0.6343993 ]]

 [[0.12374264 0.87958341 0.84304846]
  [0.83079792 0.20016272 0.90183389]
  [0.07249843 0.04367563 0.7196457 ]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
arr_q2 = np.diag([1,2,3,4],1).T
print(arr_q2)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [15]:
arr_q3 = np.zeros((8,8))
arr_q3[1::2,::2] = 1
arr_q3[::2,1::2] = 1
print(arr_q3)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [21]:
arr_q4 = np.random.random((3,3))
print("Original Array:\n",arr_q4)
arr_max = arr.max()
arr_min = arr.min()
arr_q4 = (arr_q4-arr_min)/(arr_max-arr_min)
print("Normalized Form:\n")
print(arr_q4)

Original Array:
 [[1.60997301e-01 1.73042225e-01 4.71413590e-01]
 [2.58204884e-01 9.93615325e-01 6.20331838e-01]
 [1.47681954e-01 3.76974198e-04 4.59898750e-01]]
Normalized Form:

[[ 0.12578873  0.13870293  0.45860762]
 [ 0.23001174  1.01849641  0.61827323]
 [ 0.11151242 -0.0464235   0.44626176]]


# 5.  How to find common values between two arrays?

In [24]:
arr_q5_1 = np.array([1,2,3,4,5])
print("First Array:\n", arr_q5_1)
arr_q5_2 = np.array([8,10,3,5])
print("First Array:\n", arr_q5_2)
print("CommonValues between the two arrays:\n")
print(np.intersect1d(arr_q5_1,arr_q5_2))

First Array:
 [1 2 3 4 5]
First Array:
 [ 8 10  3  5]
CommonValues between the two arrays:

[3 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [26]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's Date: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today's Date: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's Date: ",tomorrow)

Yestraday's Date:  2020-07-27
Today's Date:  2020-07-28
Tomorrow's Date:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [38]:
arr_q7_1 = np.random.randint((3,3,3))
print("First Array:",arr_q7_1)
arr_q7_2 = np.random.randint((3,3,3))
print("Second Array:",arr_q7_2)
print("Lets Compare:")
print("Are the two random arrays equal:",np.allclose(arr_q7_1,arr_q7_2))

First Array: [2 1 0]
Second Array: [1 2 1]
Lets Compare:
Are the two random arrays equal: False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [44]:
vec_q8 = np.random.random(10)
print("Original Vector:")
print(vec_q8)
vec_q8[vec_q8.argmax()] = 0
print("Vector after Replacement:\n",vec_q8)

Original Vector:
[0.85409106 0.27568666 0.56816471 0.91258471 0.3228196  0.80868208
 0.93983635 0.14064396 0.08817256 0.32218166]
Vector after Replacement:
 [0.85409106 0.27568666 0.56816471 0.91258471 0.3228196  0.80868208
 0.         0.14064396 0.08817256 0.32218166]


# 9. How to print all the values of an array?

In [46]:
arr_q9 = np. arange(10)
print(arr_q9)
    

[0 1 2 3 4 5 6 7 8 9]


# 10.Subtract the mean of each row of a matrix

In [50]:
arr_q10 = np.random.rand(4,4)
print("Initial Matrix:",arr_q10)
arr_q10_1 = arr_q10 - arr_q10.mean(axis=1, keepdims=True)
print("\nMatrix after the subtraction of mean:",arr_q10_1)

Initial Matrix: [[0.64262948 0.27674731 0.60145296 0.75797195]
 [0.00196684 0.37502834 0.39567142 0.60438769]
 [0.1237617  0.63954053 0.9000738  0.02784781]
 [0.47792    0.68214376 0.58248918 0.91773201]]

Matrix after the subtraction of mean: [[ 0.07292906 -0.29295312  0.03175253  0.18827153]
 [-0.34229673  0.03076477  0.05140785  0.26012412]
 [-0.29904426  0.21673457  0.47726784 -0.39495815]
 [-0.18715124  0.01707253 -0.08258206  0.25266077]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [52]:
vec_q11 = np.ones(5)
vec_q11_1 = np.random.randint(0,len(vec_q11),10)
vec_q11 += np.bincount(vec_q11_1, minlength=len(vec_q11))
print(vec_q11)

[2. 1. 4. 5. 3.]


# 12.How to get the diagonal of a dot product?

In [28]:
import numpy as np
vec_q12_1 = np.random.randint(1,3,(3,3))
print("Vector 1:\n", vec_q12_1)
vec_q12_2 = np.random.randint(1,3,(3,3))
print("Vector 2:\n", vec_q12_2)
product_q12 = vec_q12_1.dot(vec_q12_2)
print("Dot Product:\n", product_q12,"\n")
print("Diagonal of the dot product:", np.diagonal(product_q12))

Vector 1:
 [[2 1 1]
 [1 2 2]
 [1 1 2]]
Vector 2:
 [[1 2 2]
 [1 2 2]
 [2 1 1]]
Dot Product:
 [[5 7 7]
 [7 8 8]
 [6 6 6]] 

Diagonal of the dot product: [5 8 6]


# 13.How to find the most frequent value in an array?

In [35]:
arr_q13 = np.random.randint(0,5,5)
print("Initial array:")
print(arr_q13)
print("Most frequent value:\n ",np.bincount(arr_q13).argmax())

Initial array:
[4 4 1 1 4]
Most frequent value:
  4


# 14.How to get the n largest values of an array

In [87]:
import numpy as np
arr_q14 = np.arange(8)
print("Initial array:")
np.random.shuffle(arr_q14)
print(arr_q14)
print(arr_q14[np.sort(arr_q14)[-1:]])

Initial array:
[1 2 6 3 5 0 4 7]
[7]


# 15.How to create a record array from a regular array?

In [89]:
import numpy as np
arr_q15_1=np.array([1,2,3])
arr_q15_2=np.array(['a','b','c'])
arr_q15_3=np.array([1.2,3.5,4.1])
final_arr= np.core.records.fromarrays([arr_q15_1, arr_q15_2, arr_q15_3])
print(final_arr)


[(1, 'a', 1.2) (2, 'b', 3.5) (3, 'c', 4.1)]
